import type { NextPage } from "next";
import Head from "next/head";
import BottomSection from "../src/components/home-page/bottom-section";
import TopSection from "../src/components/home-page/top-container";

const Home: NextPage = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <TopSection />
        <BottomSection />
    </>
);

export default Home;
