import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { generate } from "randomstring";
import React from "react";
import { apiScope, authorizationURL, clientId, redirectURI } from "../src/constants";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Link
                    href={`${authorizationURL}?response_type=code&client_id=${clientId}&scope=${apiScope}&redirect_uri=${redirectURI}&state=${generate(
                        16
                    )}&show_dialog=true`}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <a>click me</a>
                </Link>
            </main>
        </div>
    );
};

export default Home;
