import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { generate } from "randomstring";
import React from "react";
import BottomSection from "../src/components/bottom-section";
import Footer from "../src/components/footer";
import Header from "../src/components/header/main-header";
import {
  apiScope,
  authorizationURL,
  clientId,
  redirectURI,
} from "../src/constants";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="blur">
        <Header />
        <main className={styles.main}>
          <Link
            href={`${authorizationURL}?response_type=code&client_id=${clientId}&scope=${apiScope}&redirect_uri=${redirectURI}&state=${generate(
              16
            )}&show_dialog=true`}
            target="_blank"
            rel="noopener noreferrer"
          >
            <a>click me</a>
          </Link>
        </main>
        <BottomSection />
        <Footer />
      </div>
    </>
  );
};

export default Home;
